name: CI/CD
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read ".node-version" file
      id: node-version
      run: echo "::set-output name=version::$(cat .node-version)"

    - name: Set up Node.js ${{ steps.node-version.outputs.version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.node-version.outputs.version }}


    - name: Find yarn cache location
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Load yarn cache
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.yarn-cache.outputs.dir }}
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/.node-version') }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node
          ${{ runner.os }}-node-${{ hashFiles('**/.node-version') }}

    - name: Install dependencies
      run: yarn install --pure-lockfile

    - name: Run the tests and generate coverage report
      run: yarn test --ci --coverage
      env:
        CI: true

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

    - name: Deploy
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/HarvestProfit/eda-demo.git
        yarn build
        touch build/.keep
        npx gh-pages clean -d build
        npx gh-pages -d build --user "Nick Horob <nick@harvestprofit.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
